<?php

/**
 * @file
 * Contains micon_linkit_attributes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function micon_linkit_attributes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the micon_linkit_attributes module.
    case 'help.page.micon_linkit_attributes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Micon Linkit Attributes module provides a linkit widget (using link_attributes) that allows users to add icons and custom attributes to link fields.') . '</p>';
      return $output;

    default:
  }
}
